name = "Strategems"
uuid = "054b7d4e-9922-5ad3-8b46-7dbe695a681f"
authors = ["Jacob Amos <jamos125@gmail.com>"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Indicators = "70c4c096-89a6-5ec6-8236-da8aa3bd86fd"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Temporal = "a110ec8f-48c8-5d59-8f7e-f91bc4cc0c3d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
